### ISSUE TITLE
`reduce` method missing problem.

### ISSUE THREAD

**Issue by tigerneil** [mjacar/pytorch-trpo#5]
@mjacar hi, I add `from functools import reduce` to fix missing `reduce` problem. Maybe only happen in python3.  

pr: https://github.com/mjacar/pytorch-trpo/pull/4

**Comment by mjacar** [comment]
Yeah, I just saw. Thanks! Not sure how I want to deal with that, though. I would appreciate it if you had any insight.

**Comment by tigerneil** [comment]
I made some mistake on creating pr for python 3 support. wait for my retry.

**Comment by tigerneil** [comment]
@mjacar I think you can merge now~ I will remember to pr to python3 branch:)
